### ISSUE TITLE
Command line options ignored?

### ISSUE THREAD

**Issue by wuher** [ozum/pg-generator#27]
When I run `pgen -t model -d mydb -u jedi -p jedi exec`, it still asks me all those options interactively. Am I doing something wrong?

**Comment by ozum** [comment]
Hi,

You forgot to provide template directory, try: (with your template)

`pgen exec your-template-dir -t model -d mydb -u jedi -p jedi`

If you didn't create a template, you can create a template such as sequelize:

`pgen template sequelize -t your-template-dir`

For other templates or create your own, please see **Builtin Templates** section on http://www.pg-generator.com/

**Comment by wuher** [comment]
Thank you. I had the templates generated but I got confused because it asked me all the options interactively, not just the ones that were missing.

**Comment by ozum** [comment]
It asks all questions if template name is not provided, because template name is an argument. If template name is provided it asks only missing info as you expected, because other info are options.

It is assumed, that you do not provide anything or you provide some info including template name.

For example:

Asks missing info such as password: `pgen exec your-template-dir -t model -d mydb -u jedi`

Asks everything: `pgen exec`
