### ISSUE TITLE
pg-generator options timestamps

### ISSUE THREAD

**Issue by ikostic** [ozum/pg-generator#34]
Hi,

on old package I found that you can set tableOptions timestamps: true for automatization of CreatedAt, UpdatedAt fields.

Do we have something similar on pg-generator package?

I tried to prepare options file:

    module.exports = {
        "timestamps": true    
    };

and run pgen exec --optionsfile options.js

but with no success.

**Comment by ozum** [comment]
Hi,

### In short

Yes, it supports. To add timestamps to `Cart` table, follow steps below:

- Create a file called `cutom-data.js`. You can use any file name.
- Put example code below. Change `Cart` with your table name. **Do not forget** quotes around `"true"`.
```js
module.exports = {
    Cart: {
        timestamps: "true"
    }
}
```
- Run `pgen exec --datafile custom-data.js`

Please see `test/util/custom-data.js` for an example.

### Long Description

Since `pg-generator`s aim is not only generate `sequelize` code, options are general purpose. Any data related to generated result is expected to be put in datafile.

All data put in datafile are accessible from template files, so you can modify behaviour of templates based on datafile's content.

About quotes around `"true"`. This is not a boolean value which triggers something. It is a string value which is used by templates to write into generated code.

```js
module.exports = {
    Cart: {
        timestamps: "'Some string'"
    }
}
```

generates this result for sequelize:

```js
module.exports = function(sequelize, DataTypes) {
    return sequelize.define('Company', {
        id: {
            type: DataTypes.INTEGER,
            field: 'id',
            allowNull: false,
            primaryKey: true,
            autoIncrement: true,
            comment: 'Kayıt no.'
        }, {
        schema: 'public',
        tableName: 'company',
        timestamps: 'Some string',
        comment: 'Firma.'
    });
};
```

**Comment by ikostic** [comment]
Hi,

thank you for the quick and detailed answer. Following your instructions I made it to work in few minutes.

Thanks for your help and dedicated time on this. I really appreciate it.

You can close the issue, everything is clear and straight-forward.

Regards
