### ISSUE TITLE
Generate only tables and use its definition name?

### ISSUE THREAD

**Issue by chityto** [ozum/pg-generator#44]
Hi,
I have 3 questions:
1. How can I get the columns in model exactly the same with its in database?
E.g: 
```
user_name: {
     type: DataTypes.STRING(255),
     field: 'user_name',
     allowNull: true
}
```
In my database, it has 'snake_case' format.

2. How to generate only tables? Now it gens all tables and views in DB?

3. I set a default option not to generate alias: **generateAliases: false**
However there are several models has self-associations, and when use these models with Sequelize it shows an error: 
**Error: 'as' must be defined for many-to-many self-associations**

How can I generate alias only for many-to-many self-associations?

Thank you.

**Comment by ozum** [comment]
Hi,

Most of the modifications are template based, because as you guess, there are infinite number of custom request. Actually previous libray of `pg-generator` was configuration based and there was lots of configuration options. They became impractical. Some point I understand that I cannot satisfy all requests with configurations, so I wrote this library as template based.

About your questions:

1. You can edit generated template file before exec. (For example partials/helper.nunj.html: You can change `{{ cc.attributeName or column.name | camelCase }}` to `{{ cc.attributeName or column.name | snakeCase }}` You can see all filters in docs http://www.pg-generator.com/template/filters/

2. There isn't any way for this unfortunately.

3. You can disable them by deleting them from generated template. (See relation templates in partials directory etc.)

**Comment by chityto** [comment]
Okay thank for supporting.
