### ISSUE TITLE
Duplicate relations in the same table

### ISSUE THREAD

**Issue by syndesis** [ozum/pg-generator#47]
`Sequelize [Node: 6.10.3, CLI: 2.7.0, ORM: 4.0.0]`
`pgen v3.6.0`

I have a table that has has two columns which both refer to another table like this:
```sql
CREATE TABLE process (
    process_id    serial    PRIMARY KEY,
    name          text
);
CREATE TABLE change_status (
    change_status_id    serial    PRIMARY KEY,
    name                text
);
CREATE TABLE transition (
    transition_id    serial    PRIMARY KEY,
    process          integer   REFERENCES process(process_id),
    current_state    integer   REFERENCES change_status (change_status_id),
    next_state       integer   REFERENCES change_status (change_status_id)
);
```
pgen gives me the following in the ChangeStatus model:
```javascript
ChangeStatus.belongsToMany(Process, {
        as: 'TransitionProcesses',
        through: Transition,
        foreignKey: 'current_state',
        otherKey: 'process'
});
ChangeStatus.belongsToMany(Process, {
        as: 'TransitionProcesses',
        through: Transition,
        foreignKey: 'next_state',
        otherKey: 'process'
});
```

This causes the following error: `SequelizeAssociationError: You have used the alias TransitionProcesses in two separate associations. Aliased associations must have unique aliases.`

I don't see why it's connecting change_status to the process table here.

**Comment by ozum** [comment]
Hi,

It connects `change_status` to the `process`table, because there is a many to many (m2m) relationship through  `transition` table. (Even you didn't intend to make it a many to many relationship. See: http://www.pg-structure.com/api/M2MRelation/)

`process >--- transition ----< change_status`

However pg-generateor should not generate same alias in this situation. This seems a bug. I'm examining it.

**Comment by ozum** [comment]
Hi,

It wasn't bug. This collision happen, because it is not possible to generate a name without help from developer.

I added a new document page about this issue and possible workaround.

Please update to latest version and see [new document page about relation names](http://www.pg-generator.com/relation-names/)

P.S. Since it is already public here, I used your DDL as an example. If you want it to be removed, please tell me, I will change table and column names.

Best Regards,

**Comment by syndesis** [comment]
Thanks for the quick update!  I don't mind if you use my DDL as an example.

**Comment by gary-x0pa** [comment]
Hi do you mind providing an example on how to fix this issue with a custom data file?

**Comment by ozum** [comment]
To rename "belongsToMany" relation:

```
    ...
    belongsToMany: {					// This is relation type
      ContactSecondCompanies: {			// This is original name generated by pg-generator
        as: "CustomBelongsToMany",		// This is your custom name
        foreignKey: "fake_id",			// This is foreign key of the relation to renamed.
      }
    }
```

**Comment by gary-x0pa** [comment]
Hmm with this it renames both associations how do you specify which one?

**Comment by ozum** [comment]
This method seems intended for collisions originated from different tables. Currently, you may change the template though.
