### ISSUE TITLE
defaultValue and JSONB data types

### ISSUE THREAD

**Issue by marneborn** [ozum/pg-generator#50]
I have a column with a JSONB datatype and want the defaultValue to be an empty object.
But the default coming out of pg_structure is '{}' (as opposed to {}) so my models definition has `defaultValue: '{}',` instead of the desired `defaultValue: {}`.

The issue basically comes down to, for JSONB data types the default shouldn't be a string so the clearDefault filter doesn't work.

I'm working around it by having this in my columns partial:
```
        {%- if column.default == "'{}'" -%}
            ,defaultValue: {}
        {%- elif cc.default or (column.default | clearDefault) -%}
            ,defaultValue: {{ cc.default or (column.default | clearDefault) }}
        {% endif -%}
```
But would like a better and more robust solution.
Should clearDefault take the data type as an input and parse accordingly or is a separate filter more desirable?

**Comment by ozum** [comment]
@marneborn PostgreSQL requires quotes (i.e.`'{}'`) in default values for JSONB fields. What and where did you get an error or what kind of problem does this issue cause?

Please provide a simple example code, so I can examine.

**Comment by marneborn** [comment]
A JSONB property on an instance should be an object not a string.
So the second line instead of the first.
```
                  id                  |         meta         
--------------------------------------+----------------------
 356f67e6-223b-4d05-b40a-3c00fba6e163 | "{hello: \"world\"}"
 20a4ac00-9f3d-4e73-951c-1b674bd8ef61 | {"hello": "world"}
```
Otherwise I can't query into the JSONB object 
```
postgres=# select id, meta from events where meta->>'hello' = 'world';
                  id                  |        meta        
--------------------------------------+--------------------
 20a4ac00-9f3d-4e73-951c-1b674bd8ef61 | {"hello": "world"}
(1 row)
```

If the model definition is 
```
  meta: {
    type: DataTypes.JSONB,
    field: 'meta',
    allowNull: false,
    defaultValue: '{}',
  },
```

Then if I do `Table.create()` the returned instance has `{ meta: "{}" }`.
And the database contains: 
```
                  id                  | meta 
--------------------------------------+------
 6ec13bab-fbbe-492e-9534-f8b1155dd8e8 | "{}"
```
But if I do `Table.create({ meta: {} })` the returned instance has `{ meta: {} }`.
And the database contains: 
```
                  id                  | meta 
--------------------------------------+------
 e82d6a8a-5f64-45de-917a-05034414529d | {}
```

If the model definition is 
```
  meta: {
    type: DataTypes.JSONB,
    field: 'meta',
    allowNull: false,
    defaultValue: {},
  },
```
Then both instances the meta property is an object.

**Comment by ozum** [comment]
I examined first `pg-structure` module, then `pg` module and finally PostgreSQL docs.

## Problem
- PostgreSQL backend server returns everything as strings,
- `pg` module does some type conversion, but it does not help in this case, because default value cannot be fetched from column itself (which `pg` module converts, because it fetches actual records). However we are not dealing with actual records, instead with definitions and meta data. So it is fetched from `information_schema`, which related column has type of `string`.

## Would Be Solution
To produce robust and general purpose solution, it is needed to write an entire individual module which converts PostgreSQL values into JavaScript values with correct data types.

## Current Workaround Alternatives

- **Robust, resuble, but more work**: Using `column.defaultWithTypeCast` (see [doc](http://www.pg-structure.com/api/Column/#columndefaultwithtypecast-string-124-null)) instead of `column.default` in templates and provide your own custom filter based on type cast information.
- **Easy, but one off**: Provide custom data file for pg-generator to override default value for particular column (see [doc](http://www.pg-generator.com/template/directories-files/))
